# Generated by Django 2.2.6 on 2020-04-11 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200411_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='name',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
