# Generated by Django 2.2.6 on 2020-04-11 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200411_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='name',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='name',
            name='start_date',
        ),
    ]
