# Generated by Django 2.2.6 on 2020-04-11 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200411_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='name',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
