# Generated by Django 2.2.6 on 2020-04-13 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200411_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='name',
            name='coordinates',
        ),
    ]
