# Generated by Django 2.2.6 on 2020-04-13 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_name_coordinates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='name',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='name',
            name='start_date',
        ),
    ]
