# Generated by Django 2.2.6 on 2020-04-13 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200413_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='name',
            name='lang',
        ),
    ]
