# Generated by Django 2.2.6 on 2020-04-17 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_name_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='sentiment_polarity',
            field=models.CharField(default=0, max_length=5),
        ),
        migrations.AddField(
            model_name='name',
            name='sentiment_subject',
            field=models.CharField(default=0, max_length=5),
        ),
    ]
