# Generated by Django 2.2.6 on 2020-04-17 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200417_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='sentiment_polarity',
            field=models.FloatField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='name',
            name='sentiment_subject',
            field=models.FloatField(default=0, max_length=5),
        ),
    ]
