# Generated by Django 2.2.6 on 2020-04-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200417_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='latitude',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='name',
            name='longitude',
            field=models.FloatField(default=0, max_length=10),
        ),
    ]
