# Generated by Django 2.2.6 on 2020-04-19 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200419_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='latitude',
            field=models.FloatField(default=0, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='name',
            name='longitude',
            field=models.FloatField(default=0, max_length=10, null=True),
        ),
    ]
