# Generated by Django 2.2.6 on 2020-04-21 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_name_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='name',
            name='value',
            field=models.CharField(default='.', max_length=20),
        ),
    ]
