# Generated by Django 2.2.6 on 2020-05-12 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20200421_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='region_id',
            field=models.CharField(default='.', max_length=20),
        ),
        migrations.AddField(
            model_name='name',
            name='region_name',
            field=models.CharField(default='England', max_length=30),
        ),
    ]
